part of 'fixtures.dart';

// ---------------------------------------------------------------------------
// Import-flow test fixtures
// ---------------------------------------------------------------------------

final FilePicker _defaultFilePickerPlatform = FilePicker.platform;

/// Builds a stable FIT binary for import-flow smoke tests.
///
/// This fixture ensures at least three timestamped GPS records with non-zero
/// point spread and includes a running session message.
Uint8List buildTestFitBytes() {
  return buildFitBytes(
    records: [
      FitTestRecord(
        timestampMs: fitBaseTimestamp,
        latitude: testLatitude,
        longitude: testLongitude,
        altitude: 12,
      ),
      FitTestRecord(
        timestampMs:
            fitBaseTimestamp + const Duration(minutes: 1).inMilliseconds,
        latitude: testLatitude + 0.0012,
        longitude: testLongitude + 0.0012,
        altitude: 20,
      ),
      FitTestRecord(
        timestampMs:
            fitBaseTimestamp + const Duration(minutes: 2).inMilliseconds,
        latitude: testLatitude + 0.0024,
        longitude: testLongitude + 0.0024,
        altitude: 28,
      ),
    ],
    sport: Sport.running,
  );
}

/// Builds a deterministic ZIP export containing FIT activities.
Uint8List buildTestZipBytes({int activityCount = 6}) {
  if (activityCount < 1) {
    throw ArgumentError.value(activityCount, 'activityCount', 'must be >= 1');
  }

  final archive = Archive();
  for (var i = 0; i < activityCount; i++) {
    final fitBytes = buildFitBytes(
      records: [
        FitTestRecord(
          timestampMs:
              fitBaseTimestamp + Duration(minutes: i * 3).inMilliseconds,
          latitude: testLatitude + i * 0.0001,
          longitude: testLongitude + i * 0.0001,
          altitude: 10.0 + i,
        ),
        FitTestRecord(
          timestampMs:
              fitBaseTimestamp + Duration(minutes: i * 3 + 1).inMilliseconds,
          latitude: testLatitude + i * 0.0001 + 0.0012,
          longitude: testLongitude + i * 0.0001 + 0.0012,
          altitude: 20.0 + i,
        ),
        FitTestRecord(
          timestampMs:
              fitBaseTimestamp + Duration(minutes: i * 3 + 2).inMilliseconds,
          latitude: testLatitude + i * 0.0001 + 0.0024,
          longitude: testLongitude + i * 0.0001 + 0.0024,
          altitude: 30.0 + i,
        ),
      ],
      sport: Sport.running,
    );
    archive.add(
      ArchiveFile.bytes(
        'activities/activity_${i.toString().padLeft(2, '0')}.fit',
        fitBytes,
      ),
    );
  }

  return Uint8List.fromList(ZipEncoder().encodeBytes(archive));
}

/// Returns the exact history-row title generated by the deterministic FIT
/// import fixtures in this file.
///
/// This keeps import E2E assertions aligned with the shared title formatter
/// and the single canonical FIT timestamp instead of relying on broad text
/// matches like `textContaining('Run')`.
String expectedImportedRunTitleForTesting({
  Duration startOffset = Duration.zero,
}) {
  final startedAt = DateTime.fromMillisecondsSinceEpoch(
    fitBaseTimestamp + startOffset.inMilliseconds,
    isUtc: true,
  );
  return generateDefaultActivityTitle(startedAt: startedAt);
}

/// Configures FilePicker to return a deterministic single picked import file.
void setNextPickedImportFile({
  required String name,
  required Uint8List bytes,
}) {
  FilePicker.platform = _FixtureFilePicker(
    result: FilePickerResult([
      PlatformFile(
        name: name,
        size: bytes.length,
        bytes: bytes,
      ),
    ]),
  );
}

/// Restores the process-global FilePicker platform implementation.
void restoreFilePickerPlatform() {
  FilePicker.platform = _defaultFilePickerPlatform;
}

// ---------------------------------------------------------------------------
// Import helper — uses banned patterns allowed only in this file
// ---------------------------------------------------------------------------

/// Programmatically invokes [ImportScreenState.runImport] via the widget tree.
///
/// This helper must live in a fixtures file because it uses `find.byType`
/// and `tester.state`, both of which are banned in test files by
/// `scripts/check_e2e_standards.sh`.
Future<void> runTestImport(
  PatrolIntegrationTester $,
  Uint8List bytes,
  String filename,
) async {
  final state = $.tester.state<ImportScreenState>(
    find.byType(ImportScreen),
  );
  await state.runImport(bytes, filename);
  await $.pumpAndSettle();
}

/// File-picker stub used by import E2E flows to return deterministic fixtures.
class _FixtureFilePicker extends FilePicker {
  _FixtureFilePicker({required this.result});

  final FilePickerResult? result;

  @override
  Future<FilePickerResult?> pickFiles({
    String? dialogTitle,
    String? initialDirectory,
    FileType type = FileType.any,
    List<String>? allowedExtensions,
    void Function(FilePickerStatus p1)? onFileLoading,
    bool allowCompression = true,
    int compressionQuality = 30,
    bool allowMultiple = false,
    bool withData = false,
    bool withReadStream = false,
    bool lockParentWindow = false,
    bool readSequential = false,
  }) async {
    return result;
  }
}
